name: ShopX CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    
    # Setup Node.js
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Install and build Backend
    - name: Install Backend Dependencies
      run: |
        cd backend
        npm ci
      
    - name: Run Backend Tests
      run: |
        cd backend
        npm test
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}

    # Install and build Frontend
    - name: Install Frontend Dependencies
      run: |
        cd frontend
        npm ci
        
    - name: Build Frontend
      run: |
        cd frontend
        npm run build
      env:
        CI: false

    # Install and build Admin Dashboard
    - name: Install Admin Dependencies
      run: |
        cd admin
        npm ci
        
    - name: Build Admin Dashboard
      run: |
        cd admin
        npm run build
      env:
        CI: false

    # Optional: Run tests if you have them
    # - name: Run tests
    #   run: |
    #     cd frontend
    #     npm test
    #     cd ../admin
    #     npm test
